
    - name: Add ceph key
      apt_key: url=https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc
      tags:
      - ceph
      become: yes

    - name: Add ceph repository
      apt_repository: repo="deb http://ceph.com/debian-dumpling/ {{ ansible_distribution_release }} main" update_cache=yes
      tags:
      - ceph
      become: yes

    - name: Install ceph storage cluster
      apt: pkg={{ item }}
      tags:
      - ceph
      with_items:
      - ceph
      - ceph-mds
      become: yes
